sudo: required

services:
  - docker

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

before_install:
  - pwd
  - npm install

script:
  - npm run compile
  - npm run coverage 
  - cat coverage/lcov.info | node_modules/.bin/coveralls
